/**
 * Maps the CSV "Set" column abbreviation to the 2-digit release number
 * used in Cerebro image URLs (e.g. Core → "01", GG → "02", etc.)
 *
 * Order follows the release order listed in Instructions.txt:
 * 1:Core 2:GG 3:A:CA 4:A:TRoRS 5:C:MM 6:A:T 7:TWC 8:A:BW 9:A:DS
 * 10:A:H 11:OaFK 12:A:A 13:A:W 14:A:Q 15:A:SW 16:G:GMW 17:G:SL
 * 18:G:G 19:G:D 20:G:V 21:G:TMTS 22:G:N 23:A:WM 24:TH 25:V
 * 26:A:V 27:W:SM 28:C:N 29:C:I 30:W:SH 31:W:S 32:C:MM(MG) 33:X:C
 * 34:X:P 35:X:MM 36:X:W 37:X:S 38:X:G 39:X:R 40:X:NE 41:X:Ps
 * 42:X:A 43:X:X 44:X:D 45:X:AoA 46:X:I 47:X:J
 *
 * Additional sets not in the original list are estimated based on
 * content in the CSV.
 */
export const SET_TO_NUMBER: Record<string, string> = {
  Core:    "01",
  GG:      "02",
  "A:CA":  "03",
  "A:TRoRS": "04",
  "C:MM":  "05",
  "A:T":   "06",
  TWC:     "07",
  "A:BW":  "08",
  "A:DS":  "09",
  "A:H":   "10",
  OaFK:    "11",
  "A:A":   "12",
  "A:W":   "13",
  "A:Q":   "14",
  "A:SW":  "15",
  "G:GMW": "16",
  "G:SL":  "17",
  "G:G":   "18",
  "G:D":   "19",
  "G:V":   "20",
  "G:TMTS":"21",
  "G:N":   "22",
  "A:WM":  "23",
  TH:      "24",
  V:       "25",
  "A:V":   "26",
  "W:SM":  "27",
  "C:N":   "28",
  "C:I":   "29",
  "W:SH":  "30",
  "W:S":   "31",
  // X-Men era
  "X:C":   "33",
  "X:P":   "34",
  "X:MM":  "35",
  "X:W":   "36",
  "X:S":   "37",
  "X:G":   "38",
  "X:R":   "39",
  "X:NE":  "40",
  "X:Ps":  "41",
  "X:A":   "42",
  "X:X":   "43",
  "X:D":   "44",
  "X:AoA": "45",
  "X:I":   "46",
  "X:J":   "47",
  // Extra sets found in CSV (estimated order)
  "W:Si":  "32",
  R:       "48",
  SS:      "49",
  CW:      "50",
  BP:      "51",
  "S:F":   "52",
  "S:WS":  "53",
  "S:AoS": "54",
  "A:WMn": "55",
  "A:He":  "56",
  "X:M":   "57",
  "X:N":   "58",
  "X:MG":  "59",
  TT:      "60",
};

/**
 * Maps the friendly set name used in deck.txt to the CSV "Set" abbreviation.
 * Deck.txt uses names like "Core Set", "Captain America", etc.
 */
export const DECK_SET_NAME_TO_CSV: Record<string, string> = {
  "core set":                    "Core",
  "core":                        "Core",
  "green goblin":                "GG",
  "captain america":             "A:CA",
  "rise of red skull":           "A:TRoRS",
  "the rise of red skull":       "A:TRoRS",
  "rors":                        "A:TRoRS",
  "ms. marvel":                  "C:MM",
  "ms marvel":                   "C:MM",
  "thor":                        "A:T",
  "wrecking crew":               "TWC",
  "black widow":                 "A:BW",
  "doctor strange":              "A:DS",
  "hulk":                        "A:H",
  "kang":                        "OaFK",
  "once and future kang":        "OaFK",
  "ant-man":                     "A:A",
  "ant man":                     "A:A",
  "wasp":                        "A:W",
  "quicksilver":                 "A:Q",
  "scarlet witch":               "A:SW",
  "galaxy's most wanted":        "G:GMW",
  "galaxys most wanted":         "G:GMW",
  "gmw":                         "G:GMW",
  "star-lord":                   "G:SL",
  "starlord":                    "G:SL",
  "gamora":                      "G:G",
  "drax":                        "G:D",
  "venom":                       "G:V",
  "the mad titan's shadow":      "G:TMTS",
  "mad titan's shadow":          "G:TMTS",
  "the mad titans shadow":       "G:TMTS",
  "mts":                         "G:TMTS",
  "nebula":                      "G:N",
  "war machine":                 "A:WM",
  "the hood":                    "TH",
  "valkyrie":                    "V",
  "vision":                      "A:V",
  "sinister motives":            "W:SM",
  "nova":                        "C:N",
  "ironheart":                   "C:I",
  "spider-ham":                  "W:SH",
  "spider ham":                  "W:SH",
  "sp//dr":                      "W:S",
  "spdr":                        "W:S",
  "silk":                        "W:Si",
  "cyclops":                     "X:C",
  "phoenix":                     "X:P",
  "mojo mania":                  "X:MM",
  "wolverine":                   "X:W",
  "storm":                       "X:S",
  "gambit":                      "X:G",
  "rogue":                       "X:R",
  "next evolution":              "X:NE",
  "neXt evolution":              "X:NE",
  "psylocke":                    "X:Ps",
  "angel":                       "X:A",
  "x-23":                        "X:X",
  "deadpool":                    "X:D",
  "age of apocalypse":           "X:AoA",
  "aoa":                         "X:AoA",
  "iceman":                      "X:I",
  "jubilee":                     "X:J",
  "ronan":                       "R",
  "civil war":                   "CW",
  "secret wars":                 "SS",
  "black panther":               "BP",
  "falcon":                      "S:F",
  "winter soldier":              "S:WS",
  "agents of shield":            "S:AoS",
  "wonder man":                  "A:WMn",
  "hercules":                    "A:He",
  "magneto":                     "X:M",
  "nightcrawler":                "X:N",
  "colossus":                    "X:MG",
  "enchantress":                 "TT",
};
